language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - pip install --user cpp-coveralls
  - luarocks install Lua-cURL         --server=https://luarocks.org/dev
  - luarocks install luacov-coveralls --server=https://luarocks.org/dev
  - luarocks install lunitx
  - luarocks install luacov-coveralls

install:
  - luarocks make rockspecs/foo-scm-0.rockspec CFLAGS="-O2 -fPIC -ftest-coverage -fprofile-arcs" LIBFLAG="-shared --coverage"

script:
  - lua -e "print(require'cURL'.version())"
  - lua -lluacov test.lua

after_success:
#  - coveralls -b .. -r .. -i ./src --dump c.report.json
#  - luacov-coveralls -j c.report.json -v
   - luacov-coveralls

notifications:
  email:
    on_success: change
    on_failure: always